version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  database:
    image: nouchka/sqlite3
    volumes:
      - ./database:/root/db
